spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
  kafka:
      bootstrap-servers: "localhost:9092"  # prevents binding failure on missing env var

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
